Repository State-of-Rhode-Island-eCMS/ecms_distribution, pull requests merged in 2020-12, with the labels that each got.

#46 Prepare for the 0.2.7 release.
  CHANGELOG.md
  composer.json
  composer.lock
Labels: drupal, release, security

#47 Rig 158/force https
  CHANGELOG.md
  factory-hooks/pre-settings-php/protocol.php
Labels: Configuration, drupal, php

#48 Update pattern lab and the ecms profile, prepare changelog for 0.2.8
  CHANGELOG.md
  composer.json
  composer.lock
Labels: release

#49 Hot fix drush deployment
  CHANGELOG.md
  factory-hooks/pre-settings-php/protocol.php
Labels: php

#50 Prepare for 0.2.9 release
  CHANGELOG.md
Labels: release

#51 Updated Pattern Lab and Profile for 0.3.0 release
  CHANGELOG.md
  composer.json
  composer.lock
Labels: Configuration, release

#52 Resolve file write warning in Drupal status
  .gitignore
  CHANGELOG.md
  config/default/.htaccess
Labels: Configuration, drupal

#53 Site Factory install error for new sites
  CHANGELOG.md
  factory-hooks/pre-settings-php/protocol.php
Labels: bug, drupal, php

#54 Prepare for the 0.3.1 release
  CHANGELOG.md
  composer.json
  composer.lock
Labels: Configuration, drupal, release

#55 Prepare for the 0.3.2 release.
  CHANGELOG.md
  composer.json
  composer.lock
Labels: release

#56 Updated the dependencies and prepare changelog for 0.3.3
  CHANGELOG.md
  composer.json
  composer.lock
Labels: approved, release

#58 Webform libraries
  CHANGELOG.md
  composer.json
  composer.lock
Labels: Configuration, approved, drupal

#59 Update and prepare for the 0.3.5 release.
  CHANGELOG.md
  composer.json
  composer.lock
Labels: Configuration, release

#60 Prepare for 0.3.6
  CHANGELOG.md
  composer.json
  composer.lock
Labels: approved, release

#61 Add memcache include file
  CHANGELOG.md
  docroot/sites/default/settings.php
  factory-hooks/post-settings-php/acsfd8+.memcache.settings.php
Labels: drupal, php

#62 Release/0.3.7
  CHANGELOG.md
  composer.json
  composer.lock
Labels: drupal, release

#65 Prepare changelog for the 1.0.0 release tag.
  CHANGELOG.md
  composer.json
  composer.lock
Labels: release

#66 Prepare for the 1.0.1 release
  CHANGELOG.md
  composer.json
  composer.lock
Labels: release

#67 Update the profile and prepare changelog for 1.0.2
  CHANGELOG.md
  composer.json
  composer.lock
Labels: release
