Repository State-of-Rhode-Island-eCMS/ecms_distribution, pull requests merged in 2020-10, with the labels that each got.

#6 Update the distribution 2020-10-06
  CHANGELOG.md
  composer.json
  composer.lock
  gulpfile.js
Labels: Configuration, approved

#7 Update composer lock file
  CHANGELOG.md
  composer.lock
Labels: Configuration, json

#8 Added feature revert to the database update cloud hook
  CHANGELOG.md
  factory-hooks/db-update/site-update.sh
Labels: approved, bash

#9 Updated the ecms profile to 0.1.0.
  CHANGELOG.md
  composer.json
  composer.lock
Labels: Configuration, drupal

#10 Prepare changelog for 0.1.2 release
  CHANGELOG.md
Labels: release

#12 Updated the distribution profile and pattern lab tags
  CHANGELOG.md
  composer.json
  composer.lock
  factory-hooks/db-update/site-update.sh
Labels: Configuration, approved, bash

#13 Prepare the changelog for 0.1.3
  CHANGELOG.md
Labels: approved, release

#14 2020-10-22 Site Updates
  CHANGELOG.md
  composer.json
  composer.lock
Labels: Configuration, drupal

#15 Prepare changelog for 0.1.4 release
  CHANGELOG.md
Labels: release

#16 Fix the features import drush command
  CHANGELOG.md
  factory-hooks/db-update/site-update.sh
Labels: approved, bash

#17 Update Pattern Lab and Profile dependencies
  .github/workflows/build-and-deploy.yml
  CHANGELOG.md
  composer.json
  composer.lock
Labels: Configuration, drupal

#18 Prepare changelog for 0.1.5 release
  CHANGELOG.md
Labels: release

#19 Updates for 10/28/2020 release
  CHANGELOG.md
  composer.json
  composer.lock
Labels: Configuration, approved, drupal

#20 Prepare changelog for 0.1.6 release
  CHANGELOG.md
Labels: approved, release

#21 2020-10-30 updates
  .lando.yml
  CHANGELOG.md
  composer.json
  composer.lock
Labels: Configuration, approved, drupal

#22 Prepare changelog for 0.1.7 release
  CHANGELOG.md
Labels: release

#23 Updated pattern lab to use 0.1.5.
  CHANGELOG.md
  composer.json
  composer.lock
Labels: Configuration, approved

#24 Prepare changelog for 0.1.8 release
  CHANGELOG.md
Labels: approved, release

#25 Update ecms_profile to 0.1.6
  CHANGELOG.md
  composer.json
  composer.lock
Labels: approved, release
