Repository State-of-Rhode-Island-eCMS/ecms_distribution, pull requests merged in 2020-11, with the labels that each got.

#26 Add config directory and post settings hook
  .gitignore
  CHANGELOG.md
  config/default/.gitkeep
  factory-hooks/post-settings-php/config.php
Labels: Configuration, drupal, php

#27 Update the pattern lab and profile dependencies
  CHANGELOG.md
  composer.json
  composer.lock
Labels: Configuration, approved, drupal

#28 Prepare changelog for 0.1.10 release.
  CHANGELOG.md
Labels: release

#29 Update pattern lab to 0.1.7
  CHANGELOG.md
  composer.json
  composer.lock
Labels: Configuration

#30 Prepare changelog for 0.1.11
  CHANGELOG.md
Labels: release

#31 Update packages and prep changelog
  CHANGELOG.md
  composer.json
  composer.lock
Labels: approved, drupal, json, release

#32 Update Pattern Lab and Ecms Profile to the 0.1.9 releases
  CHANGELOG.md
  composer.json
  composer.lock
Labels: Configuration

#33 Prepare changelog for 0.1.13
  CHANGELOG.md
Labels: release

#34 Update the pattern lab and profile versions to 0.2.0.
  CHANGELOG.md
  composer.json
  composer.lock
Labels: Configuration, drupal

#35 Prepare changelog for 0.2.0 release.
  CHANGELOG.md
Labels: release

#36 Distribution update 2020-11-13
  CHANGELOG.md
  composer.json
  composer.lock
Labels: Configuration

#37 Prepare changelog for 0.2.1.
  CHANGELOG.md
Labels: release

#38 Prepare release 0.2.2
  CHANGELOG.md
  composer.json
  composer.lock
Labels: approved

#39 Updates core to 9.0.8
  CHANGELOG.md
  composer.lock
Labels: approved, drupal, security

#40 Updated the profile and pattern lab repos
  CHANGELOG.md
  composer.json
  composer.lock
Labels: Configuration

#41 Prepare changelog for 0.2.3 tag
  CHANGELOG.md
Labels: approved, release

#42 Update pattern lab and prepare for the 0.2.4 release
  CHANGELOG.md
  composer.json
  composer.lock
Labels: release

#43 Update the pattern lab and profile dependencies, prepare for 0.2.5 tag
  CHANGELOG.md
  composer.json
  composer.lock
Labels: release

#44 fix config directories
  CHANGELOG.md
  factory-hooks/post-settings-php/config.php
Labels: Configuration, drupal, php
