Repository State-of-Rhode-Island-eCMS/ecms_distribution, pull requests merged in 2022-09, with the labels that each got.

#182 September module updates
  CHANGELOG.md
  composer.json
  composer.lock
Labels: json, drupal

#183 Prepare CHANGELOG and update dependencies for 1.7.6 release
  CHANGELOG.md
  composer.json
  composer.lock
Labels: release

#181 php8
  .lando.yml
  composer.json
  composer.lock
Labels: work in progress

#186 Upgrade drupal/core 9.4.5 => 9.4.7 (with all dependencies)
  CHANGELOG.md
  composer.lock
Labels: json, drupal, security

#187 Prepare CHANGELOG for 1.7.8 release
  CHANGELOG.md
Labels: release
