Repository State-of-Rhode-Island-eCMS/ecms_distribution, pull requests merged in 2023-02, with the labels that each got.

#216 SA-CONTRIB-2023-004 Upgrade media library form element
  CHANGELOG.md
  composer.lock
Labels: json, security

#209 Update Acquia Search to 3.1.4
  CHANGELOG.md
  composer.lock
  factory-hooks/post-settings-php/solr-core-override.php
Labels: php, json

#217 February contributed module updates
  CHANGELOG.md
  composer.lock
Labels: json, drupal

#218 Prepare CHANGELOG for 1.8.8 release
  CHANGELOG.md
Labels: release
