Repository State-of-Rhode-Island-eCMS/ecms_distribution, pull requests merged in 2024-08, with the labels that each got.

#306 Switch from Ansible-based CI workflow to direct Actions workflow
  .github/workflows/build-and-deploy.yml
  CHANGELOG.md
  oomph-actions/retrieve-infra-repo.sh
  oomph-actions/vars.yml
Labels: bug

#307 Switch from Ansible-based CI workflow to direct Actions workflow V2
  .github/workflows/build-and-deploy.yml
Labels: bug

#310 Add emergency notification feature
  .github/workflows/build-and-deploy.yml
  CHANGELOG.md
  factory-hooks/db-update/site-update.sh
  oomph-actions/retrieve-infra-repo.sh
  oomph-actions/vars.yml
Labels: script

#311 Release Candidate for 2.1.0
  .github/workflows/build-and-deploy.yml
  CHANGELOG.md
  composer.json
  composer.lock
  factory-hooks/db-update/site-update.sh
  factory-hooks/post-settings-php/secrets.php
Labels: release candidate
